#!/bin/sh

php build-env

if [ -z "$1" ]; then
  echo Available targets:
  echo
  ls .environments/
  echo

  echo Usage $0 [target]
  exit
fi

while read line
do
    if echo $line | grep -F = &>/dev/null
    then
        name=$(echo "$line" | cut -d '=' -f 1)
        value=$(echo "$line" | cut -d '=' -f 2-)
        declare $name=$value
    fi
done < .environments/$1
