#!/usr/bin/php
<?php

use Symfony\Component\Yaml\Yaml;

require 'vendor/autoload.php';

const FOLDER = '.environments';

$environments = Yaml::parseFile('environments.yaml');

if (false === is_dir(FOLDER)) {
    mkdir(FOLDER);
}

foreach ($environments as $name => $environment) {
    file_put_contents(sprintf('%s/%s', FOLDER, $name), render($environment));
}

function render(array $environment) {
    $lines = [];

    foreach ($environment as $key => $value) {
        $lines[] = sprintf('%s=%s', $key, $value);
    }

    return implode(PHP_EOL, $lines).PHP_EOL;
}
